wolfssl: Refactor `Session` creation to remove unsafe `Context::ctx()` call
Callers should now use `Context::new_session(config)` instead of
`Session::new_from_context(ctx, config)`.

The `Context::ctx()` is unsafe to force callers to check they only use the
pointer for read-only operations.

That's actually a hard `unsafe` use to audit since it isn't always clear when
an operation in the FFI might be considered a "write". However the only user of
the raw pointer was `Session::new_from_context() which was calling
`wolfSSL_new()` on it (which is allowed), with a little bit of refactoring we
can avoid the need for `::ctx()` to exist at all.

Doing this will allow us to eventually enable the
`multiple_unsafe_ops_per_block` lint, which previously failed with:

```
error: this `unsafe` block contains 2 unsafe operations, expected only one
   --> wolfssl/src/ssl.rs:227:19
    |
227 |         let ptr = unsafe { wolfssl_sys::wolfSSL_new(ctx.ctx().as_ptr()) };
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: unsafe function call occurs here
   --> wolfssl/src/ssl.rs:227:28
    |
227 |         let ptr = unsafe { wolfssl_sys::wolfSSL_new(ctx.ctx().as_ptr()) };
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: unsafe method call occurs here
   --> wolfssl/src/ssl.rs:227:53
    |
227 |         let ptr = unsafe { wolfssl_sys::wolfSSL_new(ctx.ctx().as_ptr()) };
    |                                                     ^^^^^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#multiple_unsafe_ops_per_block
    = note: requested on the command line with `-D clippy::multiple-unsafe-ops-per-block`
```