Fix cargo deny CI failure
Cargo deny CI started throwing errors recently after rust 1.83.0 upgrade:

Error:
```
2024-12-03 12:39:37 [ERROR] failed to fetch crates: warning: /github/workspace/wolfssl/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

this Cargo does not support nightly features, but if you
switch to nightly channel you can pass
`-Zlints` to enable this feature.
error: failed to parse lock file at: /github/workspace/Cargo.lock
2024-12-03 12:39:37 [ERROR] failed to fetch crates: warning: /github/workspace/wolfssl/Cargo.toml: unused manifest key `lints` (may be supported in a future version)
```

Updated the github action version which has the fix for this update:
https://github.com/EmbarkStudios/cargo-deny-action/releases/tag/v2.0.4