Fix clippy error.
PR #10 added a lint, which was not caught because we didn't have CI linting
yet (but will soon).

```
error: use of `expect` followed by a function call
  --> tests/ping_pong.rs:63:10
   |
63 |         .expect(&format!("[{who}] Poll for readiness"));
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try this: `unwrap_or_else(|_| panic!("[{who}] Poll for readiness"))`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#expect_fun_call
   = note: `-D clippy::expect-fun-call` implied by `-D warnings`

```